/* The following code was generated by JFlex 1.6.1 */

package is.iclt.icenlp.core.icestagger;
import java.util.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>EnglishTokenizer.flex</tt>
 */
public class EnglishTokenizer extends Tokenizer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\15\1\104\1\104\1\14\22\0\1\101\1\52\1\54"+
    "\1\30\1\37\1\31\1\30\1\36\1\46\1\42\1\54\1\31\1\51"+
    "\1\27\1\26\1\24\1\20\1\102\1\103\1\45\6\20\1\6\1\34"+
    "\1\44\1\41\1\50\1\53\1\32\2\33\1\75\1\5\1\72\1\23"+
    "\1\100\1\21\1\11\3\33\1\76\1\73\1\40\1\22\1\33\1\77"+
    "\1\10\1\3\1\74\1\33\1\25\1\33\1\47\1\33\1\1\1\30"+
    "\1\12\1\43\1\7\1\54\2\33\1\75\1\5\1\72\1\23\1\100"+
    "\1\21\1\11\3\33\1\76\1\73\1\40\1\22\1\33\1\77\1\10"+
    "\1\3\1\74\1\33\1\25\1\35\1\47\1\33\3\54\1\30\6\0"+
    "\1\16\32\0\1\13\37\54\27\57\1\54\37\57\1\54\70\57\2\4"+
    "\115\57\1\2\u01f0\0\220\60\u0200\0\140\61\12\62\206\61\12\62\6\61"+
    "\120\0\60\61\100\0\12\17\u0136\0\146\63\12\64\20\63\146\0\12\17"+
    "\166\0\12\17\166\0\12\17\166\0\12\17\166\0\12\17\166\0\12\17"+
    "\166\0\12\17\166\0\12\17\166\0\12\17\140\0\12\17\166\0\12\17"+
    "\106\0\12\17\u0116\0\12\17\106\0\12\17\146\0\u0100\66\u05e0\0\12\17"+
    "\46\0\12\17\u012c\0\12\17\200\0\12\17\246\0\12\17\6\0\12\17"+
    "\266\0\12\17\126\0\12\17\206\0\12\17\6\0\12\17\166\0\60\63"+
    "\u0200\0\u0100\60\16\13\2\0\30\54\1\56\1\56\33\54\u0fbb\0\1\55"+
    "\37\54\40\0\300\65\60\0\140\66\u0270\0\u19c0\67\100\0\u5200\67\u0620\0"+
    "\12\17\u02a6\0\12\17\6\0\40\63\12\17\126\0\40\66\120\0\12\17"+
    "\26\0\12\17\126\0\12\17\u0196\0\12\17\u2bb6\0\120\66\100\71\60\70"+
    "\u0790\71\u1b50\0\u02b0\61\160\0\220\61\20\0\12\17\113\0\73\65\u0500\0"+
    "\12\17\u0bbc\0\12\17\200\0\12\17\74\0\12\17\220\0\12\17\u0116\0"+
    "\12\17\u01d6\0\12\17\u0176\0\12\17\146\0\12\17\u0216\0\12\17\u5176\0"+
    "\12\17\346\0\12\17\u6c74\0\62\17\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u280f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\4\3\2\2\2\3\1\2\1\4"+
    "\1\0\1\5\2\6\3\3\1\2\1\3\1\7\1\2"+
    "\1\3\2\2\1\3\6\2\1\7\2\2\1\10\1\11"+
    "\1\6\1\12\1\6\1\13\1\14\1\15\1\1\2\3"+
    "\2\6\4\0\1\3\4\0\1\3\1\0\1\3\1\16"+
    "\3\0\1\3\1\16\3\0\1\17\1\0\1\20\1\0"+
    "\1\3\2\0\3\3\1\6\1\0\1\2\1\16\2\0"+
    "\1\3\2\0\1\16\1\0\1\16\1\2\1\0\1\16"+
    "\1\0\1\3\2\0\2\3\1\0\1\3\1\0\1\3"+
    "\7\0\3\3\2\6\1\0\1\6\3\3\3\16\1\6"+
    "\3\0\2\21\4\0\1\3\1\6\1\3\1\0\1\3"+
    "\4\0\1\21\1\0\1\22\2\0\1\21\2\0\1\22"+
    "\2\21\1\23\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\105\0\212\0\317\0\u0114\0\u0159\0\u019e\0\u01e3"+
    "\0\u0228\0\u026d\0\u02b2\0\105\0\u02f7\0\u033c\0\u0381\0\u03c6"+
    "\0\u040b\0\u0450\0\u0495\0\u04da\0\u051f\0\u0564\0\u05a9\0\u05ee"+
    "\0\u0633\0\u0678\0\u06bd\0\u0702\0\u0747\0\u078c\0\u07d1\0\u0816"+
    "\0\u085b\0\u08a0\0\u08e5\0\u02f7\0\u0381\0\u092a\0\u096f\0\u09b4"+
    "\0\u09f9\0\u0a3e\0\105\0\105\0\105\0\u0a83\0\u0ac8\0\u0b0d"+
    "\0\u0b52\0\u0b97\0\u0bdc\0\u0c21\0\u0c66\0\u0228\0\u0cab\0\u0cf0"+
    "\0\u0d35\0\u0d7a\0\u0dbf\0\u0e04\0\u0e49\0\u0e8e\0\105\0\u0ed3"+
    "\0\u06bd\0\u078c\0\u0f18\0\u0f5d\0\u0f5d\0\u0fa2\0\u0fe7\0\u02f7"+
    "\0\u102c\0\u1071\0\u10b6\0\u10fb\0\u1140\0\u1185\0\u11ca\0\u120f"+
    "\0\u1254\0\u1299\0\u12de\0\u1323\0\u1368\0\u13ad\0\u13f2\0\105"+
    "\0\u1437\0\u147c\0\u0747\0\u14c1\0\u07d1\0\u1506\0\u154b\0\u1590"+
    "\0\u15d5\0\u161a\0\u165f\0\u16a4\0\u16e9\0\u172e\0\u1773\0\u17b8"+
    "\0\u17fd\0\u1842\0\u1887\0\u18cc\0\u1911\0\u1956\0\u199b\0\u19e0"+
    "\0\u1a25\0\u1a6a\0\u0cf0\0\u1aaf\0\u10b6\0\u0cab\0\u1af4\0\u1185"+
    "\0\u1b39\0\u1b7e\0\u1bc3\0\u1c08\0\u0228\0\u1c4d\0\317\0\u1c92"+
    "\0\u1cd7\0\u1d1c\0\105\0\u0228\0\u1d61\0\u1da6\0\u1deb\0\u1e30"+
    "\0\u0228\0\105\0\u1e75\0\u1eba\0\u1eff\0\u1f44\0\u1f89\0\u1fce"+
    "\0\u2013\0\u2058\0\u209d\0\u20e2\0\u2127\0\u216c\0\u21b1\0\u21f6"+
    "\0\u223b\0\u2280\0\u22c5\0\u230a\0\105\0\u1a25";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\2\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\14"+
    "\1\11\1\14\1\5\1\10\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\21\1\41\1\5\1\14"+
    "\1\42\2\43\1\14\1\44\1\45\1\4\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\2"+
    "\1\57\3\5\1\60\2\5\1\15\1\61\1\62\110\0"+
    "\1\63\5\0\1\63\76\0\4\4\2\0\2\4\6\0"+
    "\4\4\1\0\1\4\1\0\1\64\3\0\1\4\1\0"+
    "\1\4\1\65\1\0\1\4\4\0\1\4\1\0\1\4"+
    "\7\0\1\4\12\0\7\4\1\0\2\4\3\0\1\4"+
    "\1\5\1\4\1\5\1\0\1\66\2\5\6\0\1\67"+
    "\3\5\1\0\1\5\1\70\1\71\1\0\1\66\1\72"+
    "\1\5\1\0\1\5\1\65\1\0\1\5\4\0\1\67"+
    "\1\0\1\5\7\0\1\4\12\0\7\5\1\0\2\67"+
    "\3\0\4\4\2\0\2\4\6\0\4\4\1\0\1\4"+
    "\1\73\1\64\3\0\1\4\1\0\1\4\1\65\1\0"+
    "\1\4\4\0\1\4\1\0\1\4\7\0\1\4\12\0"+
    "\1\74\6\4\1\75\2\4\3\0\1\4\1\5\1\4"+
    "\1\76\1\77\1\66\1\12\1\5\6\0\1\67\1\5"+
    "\1\76\1\5\1\0\1\5\1\70\1\100\1\0\1\66"+
    "\1\72\1\5\1\77\1\5\1\65\1\101\1\5\1\77"+
    "\1\102\2\0\1\67\1\102\1\5\7\0\1\4\12\0"+
    "\5\5\1\103\1\5\1\0\2\67\6\0\1\104\2\0"+
    "\1\104\11\0\1\104\4\0\1\105\6\0\1\106\1\104"+
    "\1\77\1\0\1\104\3\0\1\104\41\0\1\66\1\0"+
    "\1\66\1\0\3\66\6\0\4\66\1\0\3\66\1\0"+
    "\1\66\1\72\1\66\1\0\1\66\2\0\1\66\4\0"+
    "\1\66\1\0\1\66\22\0\7\66\1\0\2\66\3\0"+
    "\1\4\1\5\1\4\1\12\1\77\1\66\1\12\1\5"+
    "\6\0\1\67\1\5\1\12\1\5\1\0\1\5\1\70"+
    "\1\100\1\0\1\66\1\72\1\5\1\77\1\5\1\65"+
    "\1\101\1\5\1\0\1\101\2\0\1\67\1\101\1\5"+
    "\7\0\1\4\12\0\7\5\1\0\2\67\3\0\1\4"+
    "\1\5\1\4\1\5\1\0\1\66\2\5\6\0\1\67"+
    "\3\5\1\0\1\5\1\107\1\71\1\0\1\66\1\72"+
    "\1\5\1\0\1\5\1\65\1\0\1\5\4\0\1\67"+
    "\1\0\1\5\7\0\1\4\12\0\1\103\6\5\1\75"+
    "\2\67\14\0\1\110\1\16\2\17\36\0\1\110\1\17"+
    "\22\0\1\110\20\0\1\17\102\0\1\17\1\111\2\112"+
    "\36\0\1\17\1\112\22\0\1\17\22\0\2\20\5\0"+
    "\1\113\16\0\1\20\14\0\1\20\1\0\1\20\15\0"+
    "\2\20\3\0\1\4\1\114\1\4\1\67\1\115\1\66"+
    "\2\67\5\0\1\20\1\21\3\67\1\0\1\67\1\116"+
    "\1\71\1\0\1\66\1\72\1\67\1\0\1\67\1\65"+
    "\1\0\1\67\4\0\1\21\1\0\1\67\7\0\1\4"+
    "\2\0\1\20\1\0\1\20\5\0\7\67\1\0\1\61"+
    "\1\62\3\0\1\4\1\24\1\4\1\5\1\0\1\66"+
    "\2\5\6\0\1\67\3\5\1\0\1\5\1\70\1\71"+
    "\1\0\1\66\1\72\1\5\1\0\1\5\1\65\1\0"+
    "\1\5\4\0\1\67\1\0\1\5\7\0\1\4\12\0"+
    "\7\5\1\0\2\67\3\0\1\4\1\5\1\4\1\76"+
    "\1\77\1\66\1\12\1\5\6\0\1\67\1\5\1\76"+
    "\1\5\1\0\1\5\1\70\1\100\1\0\1\66\1\72"+
    "\1\5\1\77\1\5\1\65\1\101\1\5\1\77\1\102"+
    "\2\0\1\67\1\102\1\5\7\0\1\4\12\0\5\5"+
    "\1\117\1\5\1\0\2\67\3\0\1\4\1\120\1\4"+
    "\1\5\1\0\1\66\2\5\6\0\1\67\3\5\1\0"+
    "\1\5\1\70\1\71\1\0\1\66\1\72\1\5\1\0"+
    "\1\5\1\65\1\0\1\5\4\0\1\67\1\0\1\5"+
    "\7\0\1\4\12\0\7\5\1\0\2\67\25\0\1\25"+
    "\62\0\1\4\1\5\1\4\1\5\1\0\1\66\2\5"+
    "\6\0\1\67\3\5\1\0\1\121\1\70\1\71\1\0"+
    "\1\66\1\72\1\5\1\0\1\5\1\65\1\0\1\5"+
    "\4\0\1\67\1\0\1\5\7\0\1\4\12\0\7\5"+
    "\1\0\2\67\4\0\1\66\1\0\1\66\1\0\3\66"+
    "\6\0\4\66\1\0\1\66\1\27\1\66\1\0\1\66"+
    "\1\72\1\66\1\0\1\66\2\0\1\66\4\0\1\66"+
    "\1\0\1\66\2\0\2\43\16\0\7\66\1\0\2\66"+
    "\4\0\1\66\1\0\1\66\1\0\3\66\5\0\1\20"+
    "\1\122\3\66\1\0\2\66\1\123\1\0\1\66\1\72"+
    "\1\66\1\0\1\66\2\0\1\66\4\0\1\122\1\0"+
    "\1\66\1\124\11\0\1\20\1\0\1\20\5\0\7\66"+
    "\1\0\2\122\3\0\1\4\1\5\1\4\1\125\1\0"+
    "\1\66\1\125\1\5\6\0\1\67\1\5\1\125\1\5"+
    "\1\0\1\5\1\70\1\126\1\0\1\66\1\72\1\5"+
    "\1\0\1\5\1\127\1\104\1\5\1\0\1\104\2\0"+
    "\1\67\1\104\1\5\7\0\1\4\12\0\7\5\1\0"+
    "\2\67\3\0\1\130\5\0\1\130\101\0\1\101\1\77"+
    "\1\0\1\101\11\0\1\101\4\0\1\131\4\0\1\77"+
    "\2\0\1\101\2\0\1\101\3\0\1\101\40\0\1\4"+
    "\1\5\1\4\1\5\1\0\1\132\2\5\6\0\1\67"+
    "\3\5\1\0\1\5\1\70\1\71\1\0\1\66\1\72"+
    "\1\5\1\0\1\5\1\65\1\0\1\5\4\0\1\67"+
    "\1\0\1\5\7\0\1\4\12\0\7\5\1\0\2\67"+
    "\6\0\1\133\14\0\1\133\17\0\1\133\3\0\1\133"+
    "\43\0\1\102\1\77\1\0\1\101\11\0\1\102\4\0"+
    "\1\131\4\0\1\77\2\0\1\101\1\0\1\77\1\102"+
    "\3\0\1\102\45\0\1\134\33\0\1\135\70\0\1\136"+
    "\14\0\1\137\1\140\44\0\1\102\1\77\1\0\1\101"+
    "\11\0\1\102\4\0\1\131\4\0\1\77\2\0\1\101"+
    "\1\0\1\77\1\102\3\0\1\102\1\141\106\0\1\42"+
    "\105\0\2\43\111\0\1\46\105\0\2\47\41\0\2\20"+
    "\5\0\1\113\16\0\1\20\13\0\1\47\1\50\1\0"+
    "\1\20\15\0\2\20\64\0\2\51\37\0\2\20\5\0"+
    "\1\113\16\0\1\20\14\0\1\20\1\51\1\52\15\0"+
    "\2\20\71\0\2\55\15\0\1\4\1\142\1\4\1\5"+
    "\1\0\1\66\2\5\6\0\1\67\3\5\1\0\1\5"+
    "\1\143\1\71\1\0\1\66\1\72\1\5\1\0\1\5"+
    "\1\65\1\0\1\5\4\0\1\67\1\0\1\5\7\0"+
    "\1\4\12\0\6\5\1\103\1\144\2\67\3\0\1\4"+
    "\1\5\1\4\1\5\1\0\1\66\2\5\6\0\1\67"+
    "\3\5\1\0\1\5\1\70\1\71\1\0\1\66\1\72"+
    "\1\5\1\0\1\5\1\65\1\0\1\5\4\0\1\67"+
    "\1\0\1\5\7\0\1\4\12\0\5\5\1\145\1\5"+
    "\1\0\2\67\3\0\1\146\1\114\1\4\1\67\1\147"+
    "\1\66\1\150\1\67\5\0\1\20\1\21\3\67\1\0"+
    "\1\67\1\116\1\71\1\0\1\66\1\72\1\67\1\0"+
    "\1\67\1\65\1\0\1\67\4\0\1\21\1\0\1\67"+
    "\7\0\1\4\2\0\1\20\1\0\1\20\5\0\7\67"+
    "\1\0\1\61\1\62\3\0\1\4\1\114\1\4\1\67"+
    "\1\151\1\66\2\67\5\0\1\20\1\21\3\67\1\0"+
    "\1\67\1\116\1\71\1\0\1\66\1\72\1\67\1\0"+
    "\1\67\1\65\1\0\1\67\4\0\1\21\1\0\1\67"+
    "\7\0\1\4\2\0\1\20\1\0\1\20\5\0\1\67"+
    "\1\152\3\67\1\152\1\67\1\0\1\61\1\62\4\0"+
    "\1\153\103\0\4\4\2\0\2\4\6\0\4\4\1\0"+
    "\1\4\5\0\1\4\1\0\1\4\2\0\1\4\4\0"+
    "\1\4\1\0\1\4\7\0\1\4\12\0\7\4\1\0"+
    "\2\4\4\0\1\130\103\0\1\4\1\67\1\4\1\67"+
    "\1\0\1\66\2\67\6\0\4\67\1\0\1\67\1\66"+
    "\1\71\1\0\1\66\1\72\1\67\1\0\1\67\1\65"+
    "\1\0\1\67\4\0\1\67\1\0\1\67\7\0\1\4"+
    "\12\0\7\67\1\0\2\67\3\0\1\154\1\66\1\0"+
    "\1\66\1\0\1\66\1\155\1\66\6\0\4\66\1\0"+
    "\3\66\1\0\1\66\1\72\1\66\1\0\1\66\2\0"+
    "\1\156\4\0\1\66\1\0\1\66\22\0\1\66\1\157"+
    "\1\66\1\160\3\66\1\0\2\66\3\0\1\4\1\67"+
    "\1\4\1\67\1\0\1\66\2\67\6\0\4\67\1\0"+
    "\1\67\2\66\1\0\1\66\1\72\1\67\1\0\1\67"+
    "\2\0\1\67\4\0\1\67\1\0\1\67\7\0\1\4"+
    "\12\0\7\67\1\0\2\67\4\0\1\161\1\0\1\161"+
    "\2\0\2\161\6\0\4\161\1\0\3\161\3\0\1\161"+
    "\1\0\1\161\2\0\1\161\4\0\1\161\1\0\1\161"+
    "\22\0\7\161\1\0\2\161\73\0\1\162\6\0\1\75"+
    "\5\0\4\4\2\0\2\4\6\0\4\4\1\0\1\4"+
    "\1\130\1\64\3\0\1\4\1\0\1\4\1\65\1\0"+
    "\1\4\4\0\1\4\1\0\1\4\7\0\1\4\12\0"+
    "\7\4\1\0\2\4\73\0\1\162\14\0\1\4\1\5"+
    "\1\4\1\76\1\77\1\66\1\12\1\5\6\0\1\67"+
    "\1\5\1\76\1\5\1\0\1\5\1\70\1\100\1\0"+
    "\1\66\1\72\1\5\1\77\1\5\1\65\1\101\1\5"+
    "\1\77\1\102\2\0\1\67\1\102\1\5\7\0\1\4"+
    "\12\0\7\5\1\0\2\67\3\0\1\4\1\67\1\4"+
    "\1\67\1\77\1\66\2\67\6\0\4\67\1\0\1\67"+
    "\2\66\1\0\1\66\1\72\1\67\1\77\1\67\2\0"+
    "\1\67\4\0\1\67\1\0\1\67\7\0\1\4\12\0"+
    "\7\67\1\0\2\67\3\0\1\4\1\5\1\4\1\5"+
    "\1\0\1\66\2\5\6\0\1\67\3\5\1\0\1\5"+
    "\1\163\1\71\1\0\1\66\1\72\1\5\1\0\1\5"+
    "\1\65\1\0\1\5\4\0\1\67\1\0\1\5\7\0"+
    "\1\4\12\0\7\5\1\0\2\67\6\0\1\104\2\0"+
    "\1\104\11\0\1\104\14\0\1\104\2\0\1\104\3\0"+
    "\1\104\43\0\1\104\2\0\1\104\11\0\1\104\4\0"+
    "\1\105\7\0\1\104\2\0\1\104\3\0\1\104\40\0"+
    "\1\154\1\66\1\0\1\66\1\0\1\66\1\155\1\66"+
    "\6\0\4\66\1\0\3\66\1\0\1\66\1\72\1\66"+
    "\1\0\1\66\2\0\1\156\4\0\1\66\1\0\1\66"+
    "\22\0\1\164\1\157\1\66\1\160\3\66\1\75\2\66"+
    "\16\0\1\112\102\0\1\112\1\111\2\112\36\0\2\112"+
    "\22\0\1\112\22\0\2\165\24\0\1\165\14\0\1\165"+
    "\1\0\1\165\15\0\2\165\3\0\1\4\1\67\1\4"+
    "\1\67\1\0\1\66\2\67\6\0\1\67\1\166\2\67"+
    "\1\0\1\67\1\66\1\71\1\0\1\66\1\72\1\67"+
    "\1\0\1\67\1\65\1\0\1\67\4\0\1\67\1\0"+
    "\1\67\7\0\1\4\12\0\7\67\1\0\2\67\4\0"+
    "\1\167\104\0\1\66\1\0\1\66\1\0\3\66\5\0"+
    "\1\165\1\170\3\66\1\0\3\66\1\0\1\66\1\72"+
    "\1\66\1\0\1\66\2\0\1\66\4\0\1\170\1\0"+
    "\1\66\12\0\1\165\1\0\1\165\5\0\7\66\1\0"+
    "\2\170\3\0\1\4\1\5\1\4\1\5\1\0\1\66"+
    "\2\5\6\0\1\67\3\5\1\0\1\5\1\70\1\71"+
    "\1\0\1\66\1\72\1\5\1\0\1\5\1\65\1\0"+
    "\1\171\4\0\1\67\1\0\1\5\7\0\1\4\12\0"+
    "\7\5\1\0\2\67\3\0\1\4\1\5\1\4\1\5"+
    "\1\0\1\66\2\5\6\0\1\67\1\5\1\172\1\5"+
    "\1\0\1\5\1\70\1\71\1\0\1\66\1\72\1\5"+
    "\1\0\1\5\1\65\1\0\1\5\4\0\1\67\1\0"+
    "\1\5\7\0\1\4\12\0\7\5\1\0\2\67\3\0"+
    "\1\4\1\5\1\4\1\5\1\0\1\66\2\5\6\0"+
    "\1\67\3\5\1\0\1\173\1\70\1\71\1\0\1\66"+
    "\1\72\1\5\1\0\1\5\1\65\1\0\1\5\4\0"+
    "\1\67\1\0\1\5\7\0\1\4\12\0\7\5\1\0"+
    "\2\67\4\0\1\66\1\0\1\66\1\0\3\66\5\0"+
    "\1\20\1\122\3\66\1\0\1\66\1\116\1\66\1\0"+
    "\1\66\1\72\1\66\1\0\1\66\2\0\1\66\4\0"+
    "\1\122\1\0\1\66\12\0\1\20\1\0\1\20\5\0"+
    "\7\66\1\0\2\122\4\0\1\66\1\0\1\66\1\0"+
    "\3\66\6\0\4\66\1\0\2\66\1\123\1\0\1\66"+
    "\1\72\1\66\1\0\1\66\2\0\1\66\4\0\1\66"+
    "\1\0\1\66\1\124\21\0\7\66\1\0\2\66\51\0"+
    "\1\124\36\0\1\4\1\5\1\4\1\125\1\0\1\66"+
    "\1\125\1\5\6\0\1\67\1\5\1\125\1\5\1\0"+
    "\1\5\1\70\1\71\1\0\1\66\1\72\1\5\1\0"+
    "\1\5\1\65\1\104\1\5\1\0\1\104\2\0\1\67"+
    "\1\104\1\5\7\0\1\4\12\0\7\5\1\0\2\67"+
    "\3\0\1\4\1\67\1\4\1\174\1\0\1\66\1\174"+
    "\1\67\6\0\2\67\1\174\1\67\1\0\1\67\2\66"+
    "\1\0\1\66\1\72\1\67\1\0\1\67\1\0\1\104"+
    "\1\67\1\0\1\104\2\0\1\67\1\104\1\67\7\0"+
    "\1\4\12\0\7\67\1\0\2\67\4\0\1\130\1\0"+
    "\1\104\2\0\1\104\11\0\1\104\4\0\1\105\7\0"+
    "\1\104\2\0\1\104\3\0\1\104\44\0\1\77\25\0"+
    "\1\77\53\0\1\66\1\0\1\66\1\0\3\66\6\0"+
    "\4\66\1\0\3\66\1\0\1\66\1\72\1\66\1\0"+
    "\1\66\2\0\1\175\4\0\1\66\1\0\1\66\22\0"+
    "\7\66\1\0\2\66\10\0\1\134\33\0\1\176\70\0"+
    "\1\136\104\0\1\136\14\0\1\137\105\0\1\140\101\0"+
    "\1\77\44\0\1\4\1\5\1\4\1\5\1\0\1\66"+
    "\2\5\6\0\1\67\3\5\1\0\1\5\1\70\1\71"+
    "\1\0\1\66\1\72\1\5\1\0\1\5\1\65\1\0"+
    "\1\5\4\0\1\67\1\0\1\5\7\0\1\4\12\0"+
    "\3\5\1\103\3\5\1\0\2\67\3\0\1\154\1\66"+
    "\1\0\1\66\1\0\1\66\1\155\1\66\6\0\4\66"+
    "\1\0\3\66\1\0\1\66\1\72\1\66\1\0\1\66"+
    "\2\0\1\156\4\0\1\66\1\0\1\66\22\0\1\66"+
    "\1\157\1\66\1\160\2\66\1\164\1\144\2\66\101\0"+
    "\1\162\6\0\1\74\1\5\1\4\1\5\1\0\1\66"+
    "\1\103\1\5\6\0\1\67\3\5\1\0\1\5\1\163"+
    "\1\71\1\0\1\66\1\72\1\5\1\0\1\5\1\65"+
    "\1\0\1\5\4\0\1\67\1\0\1\5\7\0\1\4"+
    "\12\0\7\5\1\0\2\67\3\0\1\4\1\177\2\4"+
    "\2\0\2\4\6\0\4\4\1\0\1\4\1\0\1\64"+
    "\3\0\1\4\1\0\1\4\1\65\1\0\1\4\4\0"+
    "\1\4\1\0\1\4\7\0\1\4\12\0\7\4\1\0"+
    "\2\4\3\0\1\200\1\167\4\0\1\200\76\0\1\4"+
    "\1\166\1\4\1\67\1\0\1\66\2\67\6\0\4\67"+
    "\1\0\1\67\1\66\1\71\1\0\1\66\1\72\1\67"+
    "\1\0\1\67\1\65\1\0\1\67\4\0\1\67\1\0"+
    "\1\67\7\0\1\4\12\0\7\67\1\0\2\67\4\0"+
    "\1\167\67\0\1\201\3\0\1\201\7\0\1\4\1\67"+
    "\1\4\1\166\1\0\1\66\2\67\6\0\4\67\1\0"+
    "\1\67\1\66\1\71\1\0\1\66\1\72\1\67\1\0"+
    "\1\67\1\65\1\0\1\67\4\0\1\67\1\0\1\67"+
    "\7\0\1\4\12\0\7\67\1\0\2\67\5\0\1\202"+
    "\4\0\1\202\165\0\1\203\15\0\1\66\1\0\1\66"+
    "\1\0\3\66\6\0\4\66\1\0\3\66\1\0\1\66"+
    "\1\72\1\66\1\0\1\66\2\0\1\66\4\0\1\66"+
    "\1\0\1\66\22\0\1\204\6\66\1\0\2\66\4\0"+
    "\1\66\1\0\1\66\1\0\3\66\6\0\4\66\1\0"+
    "\3\66\1\0\1\66\1\72\1\66\1\0\1\66\2\0"+
    "\1\66\4\0\1\66\1\0\1\66\22\0\5\66\1\205"+
    "\1\66\1\0\2\66\4\0\1\66\1\0\1\66\1\0"+
    "\3\66\6\0\4\66\1\0\3\66\1\0\1\66\1\72"+
    "\1\66\1\0\1\66\2\0\1\66\4\0\1\66\1\0"+
    "\1\66\22\0\1\206\1\66\1\204\4\66\1\0\2\66"+
    "\4\0\1\66\1\0\1\66\1\0\3\66\6\0\4\66"+
    "\1\0\3\66\1\0\1\66\1\72\1\66\1\0\1\66"+
    "\2\0\1\207\4\0\1\66\1\0\1\66\22\0\7\66"+
    "\1\0\2\66\4\0\1\161\1\0\1\161\2\0\2\161"+
    "\6\0\4\161\1\0\1\161\1\210\1\161\3\0\1\161"+
    "\1\0\1\161\2\0\1\161\4\0\1\161\1\0\1\161"+
    "\22\0\7\161\1\0\2\161\27\0\1\130\61\0\1\66"+
    "\1\0\1\66\1\0\3\66\6\0\4\66\1\0\1\66"+
    "\1\211\1\66\1\0\1\66\1\72\1\66\1\0\1\66"+
    "\2\0\1\66\4\0\1\66\1\0\1\66\22\0\7\66"+
    "\1\0\2\66\22\0\1\212\65\0\1\4\1\5\1\4"+
    "\1\5\1\0\1\66\2\5\6\0\1\67\2\5\1\103"+
    "\1\0\1\5\1\70\1\71\1\0\1\66\1\72\1\5"+
    "\1\0\1\5\1\65\1\0\1\5\4\0\1\67\1\0"+
    "\1\5\7\0\1\4\12\0\7\5\1\0\2\67\3\0"+
    "\1\213\1\5\1\4\1\5\1\214\1\66\1\215\1\5"+
    "\6\0\1\67\3\5\1\0\1\5\1\70\1\71\1\0"+
    "\1\66\1\72\1\5\1\0\1\5\1\65\1\0\1\5"+
    "\4\0\1\67\1\0\1\5\7\0\1\4\12\0\7\5"+
    "\1\0\2\67\3\0\1\4\1\5\1\4\1\5\1\0"+
    "\1\66\2\5\6\0\1\67\3\5\1\0\1\5\1\216"+
    "\1\71\1\0\1\66\1\72\1\5\1\0\1\5\1\65"+
    "\1\0\1\5\4\0\1\67\1\0\1\5\7\0\1\4"+
    "\12\0\7\5\1\0\2\67\3\0\1\4\1\67\1\4"+
    "\1\174\1\0\1\66\1\174\1\67\6\0\2\67\1\174"+
    "\1\67\1\0\1\67\1\66\1\71\1\0\1\66\1\72"+
    "\1\67\1\0\1\67\1\65\1\104\1\67\1\0\1\104"+
    "\2\0\1\67\1\104\1\67\7\0\1\4\12\0\7\67"+
    "\1\0\2\67\44\0\1\176\44\0\1\212\106\0\1\212"+
    "\104\0\1\217\102\0\1\66\1\0\1\66\1\0\3\66"+
    "\6\0\4\66\1\0\3\66\1\0\1\66\1\72\1\66"+
    "\1\0\1\66\2\0\1\66\4\0\1\66\1\0\1\66"+
    "\22\0\6\66\1\204\1\0\2\66\4\0\1\204\1\0"+
    "\1\66\1\0\3\66\6\0\4\66\1\0\3\66\1\0"+
    "\1\66\1\72\1\66\1\0\1\66\2\0\1\66\4\0"+
    "\1\66\1\0\1\66\22\0\7\66\1\0\2\66\4\0"+
    "\1\66\1\0\1\66\1\0\3\66\6\0\4\66\1\0"+
    "\3\66\1\0\1\66\1\72\1\66\1\0\1\66\2\0"+
    "\1\66\4\0\1\66\1\0\1\66\22\0\4\66\1\204"+
    "\2\66\1\0\2\66\4\0\1\220\1\0\1\220\2\0"+
    "\2\220\6\0\1\161\3\220\1\0\1\220\1\210\1\161"+
    "\3\0\1\220\1\0\1\220\2\0\1\220\4\0\1\161"+
    "\1\0\1\220\22\0\7\220\1\0\2\161\3\0\4\4"+
    "\1\214\1\0\2\4\6\0\4\4\1\0\1\4\1\0"+
    "\1\64\3\0\1\4\1\0\1\4\1\65\1\0\1\4"+
    "\4\0\1\4\1\0\1\4\7\0\1\4\12\0\7\4"+
    "\1\0\2\4\25\0\1\221\62\0\1\4\1\5\1\4"+
    "\1\5\1\214\1\66\2\5\6\0\1\67\3\5\1\0"+
    "\1\5\1\70\1\71\1\0\1\66\1\72\1\5\1\0"+
    "\1\5\1\65\1\0\1\5\4\0\1\67\1\0\1\5"+
    "\7\0\1\4\12\0\7\5\1\0\2\67\3\0\1\154"+
    "\1\222\1\0\1\222\1\0\1\66\2\222\6\0\4\222"+
    "\1\0\1\222\1\66\1\222\1\0\1\66\1\72\1\222"+
    "\1\0\1\222\2\0\1\222\4\0\1\222\1\0\1\222"+
    "\22\0\7\222\1\0\2\222\7\0\1\223\101\0\1\224"+
    "\1\0\1\224\2\0\2\224\6\0\1\161\3\224\1\0"+
    "\1\224\1\210\1\161\3\0\1\224\1\0\1\224\2\0"+
    "\1\224\4\0\1\161\1\0\1\224\22\0\7\224\1\0"+
    "\2\161\25\0\1\225\63\0\1\222\1\0\1\222\1\226"+
    "\1\66\2\222\6\0\4\222\1\227\1\222\1\230\1\222"+
    "\1\0\1\66\1\72\1\222\1\0\1\222\2\0\1\222"+
    "\4\0\1\222\1\0\1\222\22\0\7\222\1\0\2\222"+
    "\4\0\1\231\1\0\1\231\1\0\3\231\6\0\4\231"+
    "\1\0\1\231\1\0\1\231\3\0\1\231\1\0\1\231"+
    "\2\0\1\231\4\0\1\231\1\0\1\231\22\0\7\231"+
    "\1\0\2\231\4\0\1\232\1\0\1\232\2\0\2\232"+
    "\6\0\1\161\3\232\1\0\1\232\1\210\1\161\3\0"+
    "\1\232\1\0\1\232\2\0\1\232\4\0\1\161\1\0"+
    "\1\232\22\0\7\232\1\0\2\161\4\0\1\233\1\0"+
    "\1\233\2\0\2\233\6\0\4\233\1\0\1\233\1\0"+
    "\1\233\3\0\1\233\1\0\1\233\2\0\1\233\4\0"+
    "\1\233\1\0\1\233\22\0\7\233\1\0\2\233\21\0"+
    "\1\234\24\0\1\234\34\0\2\234\4\0\1\227\1\0"+
    "\5\227\6\0\16\227\1\0\4\227\2\0\3\227\1\0"+
    "\1\227\1\0\1\227\16\0\7\227\1\0\2\227\4\0"+
    "\1\222\1\0\1\222\1\0\1\66\2\222\6\0\4\222"+
    "\1\0\1\222\1\66\1\222\1\0\1\66\1\72\1\222"+
    "\1\0\1\222\2\0\1\222\4\0\1\222\1\0\1\222"+
    "\22\0\7\222\1\0\2\222\4\0\1\231\1\0\1\231"+
    "\1\0\3\231\1\235\5\0\4\231\1\0\1\231\1\0"+
    "\1\231\3\0\1\231\1\0\1\231\2\0\1\231\4\0"+
    "\1\231\1\0\1\231\22\0\7\231\1\0\2\231\4\0"+
    "\1\236\1\0\1\236\2\0\2\236\6\0\1\161\3\236"+
    "\1\0\1\236\1\210\1\161\3\0\1\236\1\0\1\236"+
    "\2\0\1\236\4\0\1\161\1\0\1\236\22\0\7\236"+
    "\1\0\2\161\4\0\1\233\1\0\1\233\1\226\1\0"+
    "\2\233\6\0\4\233\1\227\1\233\1\225\1\233\3\0"+
    "\1\233\1\0\1\233\2\0\1\233\4\0\1\233\1\0"+
    "\1\233\22\0\7\233\1\0\2\233\21\0\1\234\3\0"+
    "\1\227\20\0\1\234\34\0\2\234\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9039];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\1\11\1\1\1\0\34\1\3\11"+
    "\5\1\4\0\1\1\4\0\1\1\1\0\1\1\1\11"+
    "\3\0\2\1\3\0\1\1\1\0\1\1\1\0\1\1"+
    "\2\0\4\1\1\0\2\1\2\0\1\11\2\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\0\1\1\2\0\2\1"+
    "\1\0\1\1\1\0\1\1\7\0\5\1\1\0\10\1"+
    "\3\0\1\11\1\1\4\0\1\1\1\11\1\1\1\0"+
    "\1\1\4\0\1\1\1\0\1\1\2\0\1\1\2\0"+
    "\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public ArrayList<Token> readSentence() throws IOException {
    ArrayList<Token> sentence = new ArrayList<Token>();
    Token token, lastNonSpace = null, lastSpace = null;

    while((token = yylex()) != null) {
        if(token.isSpace()) {
            if(token.type == Token.TOK_NEWLINES) {
                if(!sentence.isEmpty()) return sentence;
            }
            lastSpace = token;
        } else {
            if(!sentence.isEmpty()) {
                if(lastNonSpace != null &&
                   lastNonSpace.value.endsWith(".") &&
                   lastNonSpace.value.length() > 1 &&
                   token.isCapitalized())
                {
                    yypushback(yylength());
                    return sentence;
                } else if(token.type == Token.TOK_SENT_FINAL) {
                    if(lastNonSpace != null &&
                       lastNonSpace.value.length() == 1 &&
                       lastNonSpace.isCapitalized())
                    {
                    } else {
                        sentence.add(token);
                        return sentence;
                    }
                }
            }
            // I admit this is not pretty.
            if(token.type == Token.TOK_LATIN) {
                String textLower = token.value.toLowerCase();
                int length = token.value.length();
                if(textLower.endsWith("n't")) {
                    if(textLower.equals("can't")) {
                        sentence.add(new Token(
                            Token.TOK_LATIN, token.value.substring(0,3),
                            token.offset));
                        sentence.add(new Token(
                            Token.TOK_LATIN, token.value.substring(2),
                            token.offset+2));
                    } else {
                        sentence.add(new Token(
                            Token.TOK_LATIN,
                            token.value.substring(0,length-3),
                            token.offset));
                        sentence.add(new Token(
                            Token.TOK_LATIN,
                            token.value.substring(length-3),
                            token.offset+length-3));
                    }
                } else {
                    sentence.add(token);
                }
            } else {
                sentence.add(token);
            }
            lastNonSpace = token;
        }
    }
    if(sentence.isEmpty()) return null;
    return sentence;
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public EnglishTokenizer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 522) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return(new Token(Token.TOK_UNKNOWN,yytext(),yychar));
            }
          case 20: break;
          case 2: 
            { return(new Token(Token.TOK_SYMBOL,yytext(),yychar));
            }
          case 21: break;
          case 3: 
            { return(new Token(Token.TOK_LATIN,yytext(),yychar));
            }
          case 22: break;
          case 4: 
            { return(new Token(Token.TOK_SPACE,yytext(),yychar));
            }
          case 23: break;
          case 5: 
            { return(new Token(Token.TOK_NEWLINE,yytext(),yychar));
            }
          case 24: break;
          case 6: 
            { return(new Token(Token.TOK_NUMBER,yytext(),yychar));
            }
          case 25: break;
          case 7: 
            { return(new Token(Token.TOK_SENT_FINAL,yytext(),yychar));
            }
          case 26: break;
          case 8: 
            { return(new Token(Token.TOK_GREEK,yytext(),yychar));
            }
          case 27: break;
          case 9: 
            { return(new Token(Token.TOK_ARABIC,yytext(),yychar));
            }
          case 28: break;
          case 10: 
            { return(new Token(Token.TOK_NAGARI,yytext(),yychar));
            }
          case 29: break;
          case 11: 
            { return(new Token(Token.TOK_KANA,yytext(),yychar));
            }
          case 30: break;
          case 12: 
            { return(new Token(Token.TOK_HANGUL,yytext(),yychar));
            }
          case 31: break;
          case 13: 
            { return(new Token(Token.TOK_HANZI,yytext(),yychar));
            }
          case 32: break;
          case 14: 
            { return(new Token(Token.TOK_SMILEY,yytext(),yychar));
            }
          case 33: break;
          case 15: 
            { return(new Token(Token.TOK_SPACES,yytext(),yychar));
            }
          case 34: break;
          case 16: 
            { return(new Token(Token.TOK_NEWLINES,yytext(),yychar));
            }
          case 35: break;
          case 17: 
            { return(new Token(Token.TOK_URL,yytext(),yychar));
            }
          case 36: break;
          case 18: 
            { return(new Token(Token.TOK_EMAIL,yytext(),yychar));
            }
          case 37: break;
          case 19: 
            { sentID = yytext().substring(6, yylength()-1);
            }
          case 38: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
